version: '3.9'

services:
    postgres:
        image: postgres:15
        container_name: taskmanager-db
        environment:
            POSTGRES_DB: TaskManagerDB
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend-network

volumes:
    pgdata:

networks:
    backend-network:
